# Generated by Django 4.1.2 on 2022-11-04 00:58

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barrio",
            fields=[
                ("id_barrio", models.AutoField(primary_key=True, serialize=False)),
                ("barrio", models.CharField(max_length=50, verbose_name="barrio")),
                ("comuna", models.IntegerField(verbose_name="comuna")),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee", models.CharField(max_length=15, verbose_name="empleado")),
                ("age", models.IntegerField(verbose_name="edad")),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id_genre", models.AutoField(primary_key=True, serialize=False)),
                ("genre", models.CharField(max_length=50, verbose_name="genero")),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="categoria")),
                ("duration", models.PositiveBigIntegerField(verbose_name="duracion")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=50, unique=True, verbose_name="email"),
                ),
                ("password", models.CharField(max_length=256, verbose_name="password")),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="dated_joined"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last_login"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="first_name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="last_name"
                    ),
                ),
                (
                    "cellphone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="cellphone_number"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=50, verbose_name="address"),
                ),
                (
                    "birth",
                    models.DateField(blank=True, null=True, verbose_name="birth"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default=app.models.get_default_profile_image,
                        max_length=255,
                        null=True,
                        upload_to=app.models.get_profile_image_filepath,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("CLIENT", "Client"),
                            ("GERENTE", "Gerente"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "barrio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.barrio",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.genre",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="AAAA-MM-DD"
                    ),
                ),
                (
                    "timeslot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "10:00 - 10:30"),
                            ("B", "10:30 - 11:00"),
                            ("C", "11:00 - 11:30"),
                            ("D", "11:30 - 12:00"),
                            ("E", "12:00 - 12:30"),
                            ("F", "12:30 - 13:00"),
                            ("G", "13:00 - 13:30"),
                            ("H", "13:30 - 14:00"),
                            ("I", "14:00 - 14:30"),
                            ("J", "14:30 - 15:00"),
                            ("K", "15:00 - 15:30"),
                            ("L", "15:30 - 16:00"),
                            ("M", "16:00 - 16:30"),
                            ("N", "16:30 - 17:00"),
                            ("O", "17:00 - 17:30"),
                            ("P", "17:30 - 18:00"),
                            ("Q", "18:00 - 18:30"),
                        ],
                        default="Elija el horario",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.employee"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.service"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date", "timeslot", "employee")},
            },
        ),
    ]
