# Generated by Django 4.1.2 on 2022-10-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cellphone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="cellphone_number"
            ),
        ),
    ]
