# Generated by Django 4.1.2 on 2022-10-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GELN', 'GEL-NAIL'), ('KAPN', 'KAPPING-NAIL'), ('ACRN', 'ACRYLIC-NAIL'), ('LIFT', 'LIFTING-LASHES'), ('EXTE', 'THREADING-LASHES'), ('PERF', 'PERFILADO-CEJAS'), ('THRE', 'THREADING-CEJAS'), ('FACI', 'FACIAL')], max_length=4)),
                ('duration', models.FloatField()),
            ],
        ),
    ]
