# Generated by Django 4.1.2 on 2022-10-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveBigIntegerField(),
        ),
    ]
